import type { Metadata } from "next";
import Head from 'next/head';
import { Inter } from "next/font/google";
import "./globals.css";
import Header from '../components/header';
import Footer from '../components/footer';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "RAG chatbot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <Head>
      <meta name="viewport" content="initial-scale=1.0, width=device-width" />
       {/* Add React DevTools script */}
       {process.env.NODE_ENV === 'development' && (
          // eslint-disable-next-line @next/next/no-sync-scripts
          <script src="http://localhost:8097"></script>
        )}
    </Head>
    <body>
    <Header />
      <main className={inter.className}>{children}</main>
      <Footer />
      </body>
    </html>
  );
}
